[pytest]
testpaths = py2v_transpiler/tests/translator py2v_transpiler/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --ignore=py2v_transpiler/tests/input
    -v
pythonpath = .
norecursedirs = py2v_transpiler/tests/input
